<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVaaiy1o\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVaaiy1o/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVaaiy1o.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVaaiy1o\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVaaiy1o\appProdProjectContainer([
    'container.build_hash' => 'Vaaiy1o',
    'container.build_id' => '13c5ef7a',
    'container.build_time' => 1603415985,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVaaiy1o');
